<?php

namespace App\Services;

use App\Repositories\AccountsRepository;

class AccountsService extends BaseService
{
    public function __construct(AccountsRepository $repository)
    {
        parent::__construct($repository);
    }

    public function getActiveAccounts()
    {
        return $this->repository->findActiveAccounts();
    }

    public function getAccountsByClient($clientId)
    {
        return $this->repository->findByClient($clientId);
    }

    public function createNewRecord(array $data): object
    {
        $data['created_by'] = auth()->id();
        // Account number will be auto-generated by model boot method
        unset($data['account_no']); // Remove if passed from frontend
        return parent::createNewRecord($data);
    }
}